"""
Django settings for ecocart project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t7&(9oz6g8n)q)pb41s0()k#pn4p)+z#-_)exbbjyb05!-d)&0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Ensure MEDIA_URL and MEDIA_ROOT are defined once and correctly
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'products',
    'cart',
    'wishlist',
    'reviews',
    'orders',
    'payments',
    'coupons',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecocart.urls'

STATIC_URL = '/static/'
# STATIC_ROOT is used for `collectstatic` in production, not typically for development serving
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS is for additional static files not within app's static folders
# STATICFILES_DIRS = [BASE_DIR / 'static']


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Project-level templates
        'APP_DIRS': True, # This allows Django to find templates in app's 'templates' directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Added for debug if needed
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static', # Added for static files in templates
                'django.template.context_processors.media', # Added for media files in templates
            ],
        },
    },
]

WSGI_APPLICATION = 'ecocart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Redirection URLs for authentication (using named URLs for robustness)
LOGIN_URL = 'accounts:login' # URL for the login page
LOGIN_REDIRECT_URL = 'products:list' # Where to redirect after successful login
LOGOUT_REDIRECT_URL = 'accounts:login' # Where to redirect after logout

# ecocart/settings.py

# ... (rest of your settings) ...

# Email Configuration for real-time emails
# For testing, you can use a dummy SMTP server like Python's smtpd (python -m smtpd -n -c DebuggingServer localhost:1025)
# Or use a real SMTP server like Gmail, SendGrid, Mailgun etc.

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # e.g., 'smtp.gmail.com' for Gmail, 'smtp.sendgrid.net' for SendGrid
EMAIL_PORT = 587 # 587 for TLS, 465 for SSL
EMAIL_USE_TLS = True # Use TLS for security
EMAIL_HOST_USER = 'your_email@example.com' # Your email address
EMAIL_HOST_PASSWORD = 'your_email_password' # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'EcoCart Support <support@ecocart.com>' # The email address emails will appear to come from

# For development, you might use console backend to see emails in console
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'