# Generated by Django 5.2.3 on 2025-07-03 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code users will enter (e.g., FESTIVE20, FREESHIP)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('shipping', 'Free Shipping')], default='percentage', help_text='Type of discount: Percentage, Fixed Amount, or Free Shipping', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (e.g., 0.10 for 10%, 20.00 for ₹20 fixed, 0 for free shipping)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order total required to use this coupon (optional)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True, help_text='Is this coupon currently active and usable?')),
                ('valid_from', models.DateTimeField(help_text='Date and time from which the coupon is valid')),
                ('valid_to', models.DateTimeField(help_text='Date and time until which the coupon is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
