# Generated by Django 5.2.2 on 2025-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Home', 'Home'), ('Kitchen', 'Kitchen'), ('Grocery', 'Grocery'), ('Fashion', 'Fashion'), ('Personal Care', 'Personal Care'), ('Stationery', 'Stationery'), ('Cleaning', 'Cleaning'), ('Pet Care', 'Pet Care')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('eco_friendly', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=4.0)),
                ('in_stock', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
