# Generated by Django 5.2.2 on 2025-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plastic_saved_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="e.g., '3.50' kg of plastic saved per item.", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='eco_impact_statement',
            field=models.TextField(blank=True, help_text="e.g., 'This product helps reduce carbon footprint.'", null=True),
        ),
    ]
