# Generated by Django 5.2.2 on 2025-06-26 18:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='eco_friendly',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the product (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='eco_impact_statement',
            field=models.CharField(blank=True, help_text="e.g., 'Helps save 3kg of plastic' (for tooltip)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_eco_friendly',
            field=models.BooleanField(default=True, help_text='Check if this product embodies eco-friendly principles'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price, if product is discounted (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average customer rating (0.0 to 5.0)', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=django.utils.timezone.now, help_text='A concise, attractive description for cards (2-3 lines)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Number of units currently in stock', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('kitchen', 'Kitchen'), ('fashion', 'Fashion'), ('personal_care', 'Personal Care'), ('stationery', 'Stationery'), ('cleaning', 'Cleaning'), ('pet_care', 'Pet Care'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('outdoor', 'Outdoor Gear'), ('kids_baby', 'Kids & Baby'), ('grocery', 'Grocery'), ('health', 'Health & Wellness')], default='home', help_text='Primary category of the product', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed product description (for potential future detail pages)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload product image (e.g., in media/products/)', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current selling price of the product', max_digits=10),
        ),
    ]
